sudo: required
services:
  - docker

before_install:
    - docker build -t tahakhan1010/docker-react -f dockerfile.dev .

script:
  - docker run tahakhan1010/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-React1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-2-487857302228"
  bucket_path: "Docker-React1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY